#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'Snowplow'
version: '0.0.0.1'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
analysis-paths: ["analysis"]
data-paths: ["data"]

models:
  Snowplow:
    materialized: view
    vars:
      now: 'getdate()'
    transformed:
      enabled: true
      post-hooks:
        - 'VACUUM  {{this}}'
        - 'ANALYZE {{this}}'
