
version: 2

models:
    - name: snowplow_users
      description: Contains a rollup of users with information about their first and last sessions
      
      columns:
          - name: user_snowplow_domain_id
            tests:
                - not_null
                - relationships:
                    to: ref('snowplow_page_views')
                    field: user_snowplow_domain_id
                  
          - name: inferred_user_id
            tests:
                - unique
                - not_null
                
          - name: first_session_start
            tests:
                - not_null
                
          - name: last_session_end
            tests:
                - not_null


