version: 2

models:
  - name: snowplow_base_events
    description: This table contains clickstream events from the marketing website.

    columns:      
        - name: app_id
          description: This is the application ID.
          tests: 
              - not_null
          
        - name: platform
          description:
              
        - name: etl_tstamp
          description:
              
        - name: collector_tstamp
          description: This is the time stamp for the event recorded by the collector.
              
        - name: dvce_created_tstamp
          description: This is the timestamp event was recorded on the client device.
              
        - name: event
          description: This is the type of event recorded.
              
        - name: event_id
          description:
          tests:
              - not_null
              - unique
              
        - name: txn_id
          description: This is the transaction ID set client-side, used to de-dupe records.
              
        - name: name_tracker
          description: This is the tracker namespace.
              
        - name: v_tracker
          description: This is the tracker version.
              
        - name: v_collector
          description: This is the collector version.
              
        - name: v_etl
          description: This is the version of the ETL.
              
        - name: user_id
          description: This is the unique ID set by business.
              
        - name: user_ipaddress
          description: This is the user IP address.
              
        - name: user_fingerprint
          description: This is a user fingerprint generated by looking at the individual browser features.
              
        - name: domain_userid
          description: This is the user ID set by Snowplow using 1st party cookie.
              
        - name: domain_sessionidx
          description: This is a visit / session index.
              
        - name: network_userid
          description: This is the user ID set by Snowplow using 3rd party cookie.
              
        - name: geo_country
          description:
              
        - name: geo_region
          description:
              
        - name: geo_city
          description:
              
        - name: geo_zipcode
          description:
              
        - name: geo_latitude
          description:
              
        - name: geo_longitude
          description:
              
        - name: geo_region_name
          description:
              
        - name: ip_isp
          description:
              
        - name: ip_organization
          description:
              
        - name: ip_domain
          description:
              
        - name: ip_netspeed
          description:
              
        - name: page_url
          description:
              
        - name: page_title
          description:
              
        - name: page_referrer
          description:
              
        - name: page_urlscheme
          description:
              
        - name: page_urlhost
          description:
              
        - name: page_urlport
          description:
              
        - name: page_urlpath
          description:
              
        - name: page_urlquery
          description:
              
        - name: page_urlfragment
          description:
              
        - name: refr_urlscheme
          description:
              
        - name: refr_urlhost
          description:
              
        - name: refr_urlport
          description:
              
        - name: refr_urlpath
          description:
              
        - name: refr_urlquery
          description:
              
        - name: refr_urlfragment
          description:
              
        - name: refr_medium
          description:
              
        - name: refr_source
          description:
              
        - name: refr_term
          description:
              
        - name: mkt_medium
          description:
              
        - name: mkt_source
          description:
              
        - name: mkt_term
          description:
              
        - name: mkt_content
          description:
              
        - name: mkt_campaign
          description:
              
        - name: contexts
          description:
              
        - name: se_category
          description:
              
        - name: se_action
          description:
              
        - name: se_label
          description:
              
        - name: se_property
          description:
              
        - name: se_value
          description:
              
        - name: tr_orderid
          description:
              
        - name: tr_affiliation
          description:
              
        - name: tr_total
          description:
              
        - name: tr_tax
          description:
              
        - name: tr_shipping
          description:
              
        - name: tr_city
          description:
              
        - name: tr_state
          description:
              
        - name: tr_country
          description:
              
        - name: ti_orderid
          description:
              
        - name: ti_sku
          description:
              
        - name: ti_name
          description:
              
        - name: ti_category
          description:
              
        - name: ti_price
          description:
              
        - name: ti_quantity
          description:
              
        - name: pp_xoffset_min
          description:
              
        - name: pp_xoffset_max
          description:
              
        - name: pp_yoffset_min
          description:
              
        - name: pp_yoffset_max
          description:
              
        - name: useragent
          description:
              
        - name: br_name
          description:
              
        - name: br_family
          description:
              
        - name: br_version
          description:
              
        - name: br_type
          description:
              
        - name: br_renderengine
          description:
              
        - name: br_lang
          description:
              
        - name: br_features_pdf
          description:
              
        - name: br_features_flash
          description:
              
        - name: br_features_java
          description:
              
        - name: br_features_director
          description:
              
        - name: br_features_quicktime
          description:
              
        - name: br_features_realplayer
          description:
              
        - name: br_features_windowsmedia
          description:
              
        - name: br_features_gears
          description:
              
        - name: br_features_silverlight
          description:
              
        - name: br_cookies
          description:
              
        - name: br_colordepth
          description:
              
        - name: br_viewwidth
          description:
              
        - name: br_viewheight
          description:
              
        - name: os_name
          description:
              
        - name: os_family
          description:
              
        - name: os_manufacturer
          description:
              
        - name: os_timezone
          description:
              
        - name: dvce_type
          description:
              
        - name: dvce_ismobile
          description:
              
        - name: dvce_screenwidth
          description:
              
        - name: dvce_screenheight
          description:
              
        - name: doc_charset
          description:
              
        - name: doc_width
          description:
              
        - name: doc_height
          description:
              
        - name: tr_currency
          description:
              
        - name: tr_total_base
          description:
              
        - name: tr_tax_base
          description:
              
        - name: tr_shipping_base
          description:
              
        - name: ti_currency
          description:
              
        - name: ti_price_base
          description:
              
        - name: base_currency
          description:
              
        - name: geo_timezone
          description:
              
        - name: mkt_clickid
          description:
              
        - name: mkt_network
          description:
              
        - name: etl_tags
          description:
              
        - name: dvce_sent_tstamp
          description:
              
        - name: refr_domain_userid
          description:
              
        - name: refr_dvce_tstamp
          description:
              
        - name: domain_sessionid
          description:
              
        - name: derived_tstamp
          description:
              
        - name: event_vendor
          description:
              
        - name: event_name
          description:
              
        - name: event_format
          description:
              
        - name: event_version
          description:
              
        - name: event_fingerprint
          description:
              
        - name: true_tstamp
          description:
              
        - name: _piped_at
          description:
