
version: 2

models:
    - name: snowplow_sessions
      description: {{doc('snowplow_sessions')}}
      
      columns:
          - name: session_id
            tests:
                - not_null
                - unique
                - relationships:
                    to: ref('snowplow_page_views')
                    field: session_id