
version: 2

models:
    - name: snowplow_sessions
      description: Contains a rollup of page views indexed by cookie id (user_snowplow_domain_id)
      
      columns:
          - name: session_id
            tests:
                - not_null
                - unique
                - relationships:
                    to: ref('snowplow_page_views')
                    field: session_id