

snowplow_web_events:
    constraints:
        not_null:
            - domain_userid
            - collector_tstamp
            - domain_sessionid
            - domain_sessionidx
            - page_view_id


        unique:
            - page_view_id

        relationships:
            - {from: page_view_id, to: snowplow_web_page_context, field: page_view_id }


snowplow_web_events_time:
    constraints:
        not_null:
            - page_view_id

        unique:
            - page_view_id

        relationships:
            - {from: page_view_id, to: snowplow_web_page_context, field: page_view_id }



snowplow_web_events_scroll_depth:
    constraints:
        not_null:
            - page_view_id

        unique:
            - page_view_id

        relationships:
            - {from: page_view_id, to: snowplow_web_page_context, field: page_view_id }


snowplow_web_page_context:
    constraints:
        not_null:
            - root_id
            - page_view_id

        unique:
            - root_id
            - '(page_view_id || root_id)'

        relationships:
            - {from: page_view_id, to: snowplow_web_events_time, field: page_view_id }
            - {from: page_view_id, to: snowplow_web_events_scroll_depth, field: page_view_id }
            - {from: page_view_id, to: snowplow_web_events, field: page_view_id }


snowplow_page_views:
    constraints:
        not_null:
            - user_snowplow_domain_id
            - session_id
            - session_index
            - page_view_id

        unique:
            - page_view_id
