                                 
version: 2

models:
    - name: snowplow_web_events
      description: Schema and table for web page context

      columns:
          - name: domain_userid
            tests:
                - not_null
                
          - name: collector_tstamp
            tests:
                - not_null
                
          - name: domain_sessionid
            tests:
                - not_null
                
          - name: domain_sessionid
            tests:
                - not_null
                
          - name: page_view_id
            tests:
                - not_null
                - unique
                - relationships:
                    to: ref('snowplow_web_page_context')
                    field: page_view_id
                - accepted_values:
                    field: "case when count(*) > 0 then 'True' else 'False' end"
                    values: ['True']
                    
    - name: snowplow_web_events_time
    
      columns:
          - name: page_view_id
            tests:
                - unique
                - relationships:
                    to: ref('snowplow_web_page_context')
                    field: page_view_id
                    
    - name: snowplow_web_events_scroll_depth
    
      columns:
          - name: page_view_id
            tests:
                - unique
                - relationships:
                    to: ref('snowplow_web_page_context')
                    field: page_view_id

    - name: snowplow_web_page_context
      tests:
          - unique: "concat(page_view_id, root_id)"
    
      columns:
          - name: page_view_id
            tests:
                - unique
                - not_null

          - name: root_id
            tests:
                - unique
                - not_null
                
    - name: snowplow_page_views
      description: Contains a list of pageviews with scroll depth, view timing, and optionally useragent and performance data.

      columns:
          - name: page_view_id
            tests:
                - unique
                - not_null

          - name: user_snowplow_domain_id
            tests:
                - not_null
                
          - name: session_id
            tests:
                - not_null
                
          - name: session_index
            tests:
                - not_null
